import type { Customer } from "./machines";

export const SEED: Customer[] = [
  {
    id: "c1",
    name: "青禾花艺",
    tags: ["重点客户", "零售"],
    amount: 12800,
    owner: "林悦",
    status: "待跟进",
    updatedAt: "2026-09-18",
    note: "季度花艺订购，待确认秋季配色与门店陈列节奏。",
  },
  {
    id: "c2",
    name: "山岚咖啡",
    tags: ["餐饮"],
    amount: 3600,
    owner: "陈晨",
    status: "已联系",
    updatedAt: "2026-09-16",
    note: "想升级豆仓管理，下周二试喝会。",
  },
  {
    id: "c3",
    name: "木白家居",
    tags: ["重点客户", "家居"],
    amount: 28600,
    owner: "林悦",
    status: "待跟进",
    updatedAt: "2026-09-20",
    note: "新品系列落地页与门店物料一并报价。",
  },
  {
    id: "c4",
    name: "星野烘焙",
    tags: ["餐饮"],
    amount: 8900,
    owner: "周宁",
    status: "已联系",
    updatedAt: "2026-09-14",
    note: "中秋礼盒复盘完成，下一步看冬季限定。",
  },
  {
    id: "c5",
    name: "南风书店",
    tags: ["零售"],
    amount: 6400,
    owner: "陈晨",
    status: "已完成",
    updatedAt: "2026-09-12",
    note: "会员日活动已结案，资料归档。",
  },
  {
    id: "c6",
    name: "拾光摄影",
    tags: ["服务"],
    amount: 15800,
    owner: "周宁",
    status: "待跟进",
    updatedAt: "2026-09-19",
    note: "品牌形象片分镜已出，待客户确认档期。",
  },
  {
    id: "c7",
    name: "云间民宿",
    tags: ["住宿"],
    amount: 19200,
    owner: "林悦",
    status: "已联系",
    updatedAt: "2026-09-15",
    note: "淡季套餐文案三版，等主理人回。",
  },
  {
    id: "c8",
    name: "好物集",
    tags: ["零售"],
    amount: 4200,
    owner: "陈晨",
    status: "已完成",
    updatedAt: "2026-09-10",
    note: "小程序货架整理完成。",
  },
  {
    id: "c9",
    name: "月白茶室",
    tags: ["餐饮", "重点客户"],
    amount: 21400,
    owner: "林悦",
    status: "待跟进",
    updatedAt: "2026-09-21",
    note: "茶席课程联名，需要排秋季日历。",
  },
  {
    id: "c10",
    name: "素纸工坊",
    tags: ["零售"],
    amount: 5100,
    owner: "周宁",
    status: "已联系",
    updatedAt: "2026-09-13",
    note: "纸品礼盒打样中。",
  },
  {
    id: "c11",
    name: "涧溪陶艺",
    tags: ["家居", "服务"],
    amount: 17300,
    owner: "陈晨",
    status: "待跟进",
    updatedAt: "2026-09-17",
    note: "工作室开放日海报与报名页。",
  },
  {
    id: "c12",
    name: "林间花店",
    tags: ["零售"],
    amount: 7800,
    owner: "周宁",
    status: "已完成",
    updatedAt: "2026-09-08",
    note: "婚礼花艺档案已交付。",
  },
  {
    id: "c13",
    name: "北窗书店",
    tags: ["零售", "重点客户"],
    amount: 24600,
    owner: "林悦",
    status: "已联系",
    updatedAt: "2026-09-19",
    note: "作家签售周末需要额外人力。",
  },
  {
    id: "c14",
    name: "暖石咖啡",
    tags: ["餐饮"],
    amount: 9200,
    owner: "陈晨",
    status: "待跟进",
    updatedAt: "2026-09-11",
    note: "二号店选址评估还没回。",
  },
  {
    id: "c15",
    name: "青石布艺",
    tags: ["家居"],
    amount: 13400,
    owner: "周宁",
    status: "已联系",
    updatedAt: "2026-09-09",
    note: "窗帘样卡寄出，等确认色号。",
  },
  {
    id: "c16",
    name: "晚风画廊",
    tags: ["服务", "重点客户"],
    amount: 31800,
    owner: "林悦",
    status: "待跟进",
    updatedAt: "2026-09-21",
    note: "十月联展主视觉三稿待选。",
  },
];
